require("vim.after-init-config.colors")
require("vim.after-init-config.telescope-config")
require("vim.after-init-config.fugitive-config")
-- require("vim.after-init-config.coc-config")
require("vim.after-init-config.lspconfig-nvim")
require("vim.after-init-config.gui-settings")
require("vim.after-init-config.lspsaga-nvim")
require("vim.after-init-config.gitconfig")
require("vim.after-init-config.harpoon-config")
