require("vim.after-init-config.colors")
require("vim.after-init-config.telescope-config")
require("vim.after-init-config.fugitive-config")
require("vim.after-init-config.coc-config")
require("vim.after-init-config.lspconfig-nvim")
require("vim.after-init-config.gui-settings")
