name: Lua-Lint

on: [push]

jobs:
    lint:
        name: Luacheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup
              run: |
                  sudo apt-get update
                  sudo apt-get install luarocks
                  sudo luarocks install luacheck

            - name: Lint
              run: luacheck ./ --globals vim
